### ISSUE TITLE
V1 Global Surface Temperature (line chart)

### ISSUE THREAD

**Issue by nennahanninen** [team11webdev/climate_change_app#11]
### Description
- Line chart that displays global historical surface temperature anomalies from January 1850 onwards.
- HadCRUT5 data (HadCRUT5 analysis time series: ensemble means and uncertainties).
- [Description and dataset](https://www.metoffice.gov.uk/hadobs/hadcrut5/)
- The horizontal axis of the chart should be years.

### Todo:
- [ ] Display line chart with correct data from the database
- [ ] Toggle option for monthly and annual data
- [ ] Chart is zoomable
- [ ] Plot all three data series by their anomaly values and each series with different colour:
> Global (NH+SH)/2
> Northern hemisphere
> Southern hemisphere
- [ ] Provide link to data sources
