### ISSUE TITLE
V8 CO2 Emissions By Country

### ISSUE THREAD

**Issue by nennahanninen** [team11webdev/climate_change_app#12]
### Description
- Stacked line chart presenting CO2 emissions by country.
- The horizontal (x-axis) presents years between 1959-2020.
- Dataset is in xlsx format.
- Dataset contains Territorial Emissions, Consumption Emissions, Emissions Transfers and Country Definitons. (Only Territorial Emissions needed)

### Todo:

- [x] All values in the data source is presented as million tonnes of carbon per year. For values in million tonnes of CO2 per year, multiply all the values first by 3.664. (Done in Excel before importing to the database)
- [ ]  Display stacked line chart with correct data from the database
- [ ] Provide link to data source: [Data source](https://data.icos-cp.eu/licence_accept?ids=%5B%22lApekzcmd4DRC34oGXQqOxbJ%22%5D)
- [ ] Provide link to the description: [Description](https://essd.copernicus.org/articles/14/1917/2022/)
- [ ] Include a brief description of the graph and its information

### UI Design Mockup
![Image](https://user-images.githubusercontent.com/89773208/200129391-18716e1f-ca7a-49fe-82b0-ae4f0f454492.png)
