### ISSUE TITLE
V3 CO2 Mauna Loa (line chart)

### ISSUE THREAD

**Issue by nennahanninen** [team11webdev/climate_change_app#20]
### Description
- Atmospheric CO2 concentrations from Mauna Loa measurements starting from 1958.
- A line chart to display the results of the Mauna Loa CO2 concentration measurements.
- The horizontal axis of the chart should be years.

### Todo:

- [ ] Toggle options for either monthly or annual data
> Mauna Loa CO2 monthly mean data
> Mauna Loa CO2 annual mean data
- [ ] Provide a link to data source
- [ ] Provide a link to data [Measurement description](https://gml.noaa.gov/ccgg/about/co2_measurements.html)
- [ ] Write a brief description of the graph and its information
