### ISSUE TITLE
V2 Northern Hemisphere (dependant on V1)

### ISSUE THREAD

**Issue by nennahanninen** [team11webdev/climate_change_app#24]
### Description
- Northern Hemisphere 2,000-year temperature reconstruction.
- [Description](https://bolin.su.se/data/moberg-2012-nh-1?n=moberg-2005)
- [Dataset](https://www.ncei.noaa.gov/pub/data/paleo/contributions_by_author/moberg2005/nhtemp-moberg2005.txt)

### Todo

- [ ] This dataset is added to the previous temperature chart (V1 Global historical surface temperature anomalies from January 1850 onwards) as an option, which the user can turn on and off.
- [ ] Use different colour to highlight this dataset.
- [ ] Provide a link to data [Measurement description](https://gml.noaa.gov/ccgg/about/co2_measurements.html)
- [ ] Write a brief description of the graph and its information
