### ISSUE TITLE
V10 Human Evolution + Activities (dependant on V7 + V3 & V4)

### ISSUE THREAD

**Issue by nennahanninen** [team11webdev/climate_change_app#25]
### Description
- Displays major human evolution and culture events. 
- Choose to show especially relevant events for the CO2 temperature!

### Todo:

- [ ]  Display data correctly from the database
- [ ] Toggle option added to the following charts:
> **_V7 Evolution of global temperature over the past two million years_**
> **_V4 Antarctic Ice Core records of atmospheric CO2 ratios combined with Mauna Loa measurements_**
- [ ] The events can be added to the charts as line chart points by setting the `showLine` property to false
- [ ] Information provided as **tooltips**

**Comment by nennahanninen** [comment]
Tooltip width needs to be fixed
